# Generated by Django 4.1.7 on 2023-03-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups_task',
            field=models.ManyToManyField(to='task.group'),
        ),
    ]
