# Generated by Django 4.1.7 on 2023-06-06 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_taskfile_file'),
        ('account', '0003_alter_user_options_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUserToJoinGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('expire_after_days', models.PositiveIntegerField(default=7)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
