# Generated by Django 4.1.7 on 2023-06-06 21:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_requestusertojoingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestusertojoingroup',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='requestusertojoingroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
