# Generated by Django 4.1.7 on 2023-06-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_taskfile_file'),
        ('account', '0005_requestusertojoingroup_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRequestUserToJoinGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_submit', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.group')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
