# Generated by Django 4.1.7 on 2023-07-08 14:41

import core.validators.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_requestusertojoingroup_is_active_alter_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=core.validators.decorators.validator_image_format),
        ),
        migrations.DeleteModel(
            name='HistoryRequestUserToJoinGroup',
        ),
    ]
