# Generated by Django 4.1.7 on 2023-06-24 02:46

import core.validators.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(max_length=300, upload_to=core.validators.decorators.validator_file_format),
        ),
    ]
