# Generated by Django 4.1.7 on 2023-06-27 22:38

import core.validators.decorators
import core.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
    ]
