# Generated by Django 4.1.7 on 2023-06-24 04:10

import core.validators.decorators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_label_alter_taskfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeleft',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime.now)]),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(max_length=300, upload_to=core.validators.decorators.validator_file_format),
        ),
    ]
