# Generated by Django 4.1.7 on 2023-07-01 03:38

import core.utils
import core.validators.decorators
import core.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_timeleft_alter_taskfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeleft',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(core.utils.get_datetime)]),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
        migrations.AlterField(
            model_name='taskfileresponse',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
    ]
