# Generated by Django 4.1.7 on 2023-06-25 22:38

import core.validators.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_timeleft_alter_taskfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(max_length=300, upload_to=core.validators.decorators.validator_file_format),
        ),
    ]
