# Generated by Django 4.1.7 on 2023-06-28 03:32

import core.validators.decorators
import core.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_create_by_task_created_by_alter_taskfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime_create',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datetime_update',
            new_name='datetime_updated',
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
    ]
