# Generated by Django 4.1.7 on 2023-07-02 00:54

import core.mixins.model.delete_file
import core.validators.decorators
import core.validators.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_timeleft_alter_taskfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponseFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size])),
                ('task_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskresponse')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.model.delete_file.RemovePastFileMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
        migrations.DeleteModel(
            name='TaskFileResponse',
        ),
    ]
