# Generated by Django 4.1.7 on 2023-03-30 05:30

import core.validators.decorators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_group_admins_alter_taskfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to=core.validators.decorators.validator_file_format),
        ),
    ]
