# Generated by Django 4.1.7 on 2023-07-11 17:57

import core.validators.decorators
import core.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskfile_file_alter_taskresponsefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(help_text='size file should not exceed 10 MB', max_length=3000, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
        migrations.AlterField(
            model_name='taskresponsefile',
            name='file',
            field=models.FileField(help_text='size file should not exceed 10 MB', max_length=3000, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
    ]
