# Generated by Django 4.1.7 on 2023-07-08 14:28

import core.validators.decorators
import core.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_taskresponse_user_alter_taskfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
        migrations.AlterField(
            model_name='taskresponsefile',
            name='file',
            field=models.FileField(help_text='Size file should not exceed 10 MB', max_length=300, upload_to=core.validators.decorators.validator_file_format, validators=[core.validators.validators.limit_file_size]),
        ),
    ]
